-- Create profiles
CREATE PROFILE c##travel_app_profile LIMIT 
FAILED_LOGIN_ATTEMPTS 5 
PASSWORD_LIFE_TIME 90 
PASSWORD_REUSE_TIME 60 
PASSWORD_REUSE_MAX 5;

CREATE PROFILE c##manager_profile LIMIT 
SESSIONS_PER_USER 2 
CPU_PER_SESSION 10000 
CONNECT_TIME 60 
PASSWORD_LIFE_TIME 30;

